model:
  node_dim: 3
  out_dim: 16
  layers: [64, 64, 64, 64, 64, 64]
  num_channels: 4
  neurons: 256
  nonlinearity: ReLU
data:
  k: 30
  mode: test
  scale: true
  min_z_scale: 0.001
  basis: legendre
  basis_degree: 3

